### ISSUE TITLE
安装成功后，运行camera_reading出现warn，无法显示usb相机图像，使用opencv读取正常

### ISSUE THREAD

**Issue by XinChen-stars** [amov-lab/SpireCV#1]
以下为warn信息：
global cap_gstreamer.cpp:1728 open OpenCV | GStreamer warning: Cannot query video position : status=0, value=-1, duration=-1

运用opencv：cv::VideoCapture cap(0,cv::CAP_V4L2);//可以显示

请问有什么方式可以解决这个问题吗？

**Comment by Daniellllllr** [comment]
你好 请问您使用的是什么相机 有具体型号吗？

**Comment by Daniellllllr** [comment]
代码已更新，您可以更新下代码 再试下呢？
